packages:
  - apps/*
  - packages/*
allowBuilds:
  better-sqlite3: true
  edgedriver: true
  electron: true
  esbuild: true
  geckodriver: true
  tree-sitter: true
  tree-sitter-go: true
  tree-sitter-java: true
  tree-sitter-javascript: true
  tree-sitter-python: true
  tree-sitter-rust: true
  tree-sitter-typescript: true
